---
- hosts: localhost
  vars_files:
    - ../../../install/openshift/vars_common.yml
    - ../../../install/openshift/vars_env_{{ STAGE }}.yml
  tasks:
    - name: Deploy Kafka via Operator
      when: kafkaOperatorIsAvailable
      k8s:
        state: present
        wait: true
        definition:
          apiVersion: kafka.strimzi.io/v1alpha1
          kind: Kafka
          metadata:
            name: backend-eventstore
            namespace: "{{ NAMESPACE }}"
          spec:
            kafka:
              version: 2.1.1
              replicas: 1
              listeners:
                plain: {}
                tls: {}
              config:
                offsets.topic.replication.factor: 1
                transaction.state.log.replication.factor: 1
                transaction.state.log.min.isr: 1
                log.message.format.version: "2.1"
              storage:
                type: persistent-claim
                size: 1Gi
                deleteClaim: true
            zookeeper:
              replicas: 1
              storage:
                type: persistent-claim
                size: 1Gi
                deleteClaim: true

# Ugly as hell, but i dont care.
# Need to ignore errors as no idempotency here:
    - name: Deploy Kafka via ugly workaround (errors can be ignored)
      block:
        - name: Deploy zookepper
          command: oc create -f -
          args:
            stdin: "{{ lookup('template', 'noOperator_zookeeper.yml') }}"
          ignore_errors: yes
        - name: Deploy broker
          command: oc create -f -
          args:
            stdin: "{{ lookup('template', 'noOperator_broker.yml') }}"
          ignore_errors: yes
      when: not kafkaOperatorIsAvailable
