openapi: 3.0.1
info:
  title: Simple Weather API
  description: API for getting the current weather information.
  version: "1.0"
servers:
- url: //localhost:8001/api
paths:
  /hello:
    get:
      tags:
      - /hello
      description: Returns the current weather for the requested location using the requested unit.
      operationId: helloWorldGet
      parameters:
      - name: greeting
        in: query
        description: Name of greeting
        required: true
        schema:
          type: string
      responses:
        200:
          description: Successful request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hello'
        default:
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: helloWorldRoute
    post:
      tags:
      - /hello
      description: Returns the current weather for the requested location using the requested unit.
      operationId: helloWorldPost
      parameters:
      - name: greeting
        in: query
        description: Name of greeting
        required: true
        schema:
          type: string
      responses:
        200:
          description: Successful request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hello'
        default:
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: helloWorldRoute
components:
  schemas:
    Hello:
      required:
      - msg
      type: object
      properties:
        msg:
          type: string
    Error:
      required:
      - message
      type: object
      properties:
        message:
          type: string
